---
# This playbook is an inner loop and has values i.name and i.token
- name: Inner loop through filtered_credentials_list
  ansible.builtin.set_fact:
    updated_users: >-
      {{
        updated_users | default([]) + [
          {
            'name': j.name,
            'id': j.id,
            'credential_type': j.credential_type,
            'inputs': j.inputs | combine({'password': i.token})
          }
        ]
      }}
  when: i.name == j.name
  loop: "{{ filtered_credentials_list }}"
  loop_control:
    loop_var: j
