---
- name: Update AAP credentials using API
  hosts: localhost
  gather_facts: false

  vars:
    AAP_IP: ""
    AAP_TOKEN: ""
    GIT_SERVER: GIT1 # GIT1 or GIT2 passed as extra_vars to know which server to failover to
    CYBERARK_CCP_URL: ""
    CYBERARK_CCP_CREDS_LIST_TO_PULL: ""

  tasks:
    - name: Get all credentials that are Source Control in AAP
      ansible.builtin.uri:
        url: "https://{{ AAP_IP }}/api/v2/credentials/?credential_type__namespace=scm"
        method: GET
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ AAP_TOKEN }}
        validate_certs: false
      register: credentials_res

    - name: Debug credentials_res
      ansible.builtin.debug:
        msg: "{{ credentials_res }}"

    - name: Pull creds from CCP
      cyberark.pas.cyberark_credential:
        api_base_url: "{{ CYBERARK_CCP_URL }}"
        validate_certs: true
        client_cert: "{{ AAP_CLIENT_CERT }}"
        client_key: "{{ AAP_CLIENT_KEY }}"
        app_id: "Ansible"
        query: "Safe=test;UserName=admin" # Change to query gita_admin
        connection_timeout: 60
        query_format: Exact
        fail_request_on_password_change: true
        reason: "Requesting credential for Ansible Gitlab HA playbook"
      register: cyberark_ccp_res
      loop: CYBERARK_CCP_CREDS_LIST_TO_PULL

    - name: Print cyberark_ccp_res
      ansible.builtin.debug:
        msg: "{{ cyberark_ccp_res }}"

    - name: Create credentials object with 2 fields (user, token)
      ansible.builtin.set_fact:
        ccp_cred_object_list: "{{ ccp_cred_object_list | default([]) + [{'name': item['json']['result']['Username'], 'token': item['json']['result']['Content']}] }}" 
      loop: "{{ cyberark_ccp_res.results }}"

    - name: Print ccp_cred_object_list
      ansible.builtin.debug:
        msg: "{{ ccp_cred_object_list }}"

    - name: Create credentials object list
      ansible.builtin.set_fact:
        credentials_obj_list: "{{ credentials_res.json.results }}"

    - name: Extract name, id, inputs from credentials_obj_list
      ansible.builtin.set_fact:
        filtered_credentials_list: "{{ filtered_credentials_list | default([]) + [{'name': item.name, 'id': item.id, 'inputs': item.inputs, 'credential_type': item.credential_type}] }}"
      loop: "{{ credentials_obj_list }}"

    - name: Debug filtered_credentials_list
      ansible.builtin.debug:
        msg: "{{ filtered_credentials_list }}"

    # This will return updated_users var
    - name: Outer loop over ccp_cred_object_list
      ansible.builtin.include_tasks: loop_filtered_credentials_list.yaml
      loop: "{{ ccp_cred_object_list }}"
      loop_control:
        loop_var: i

    - name: Display updated_users
      ansible.builtin.debug:
        var: updated_users

    - name: Update the credentials on AAP
      ansible.builtin.uri:
        url: "https://{{ AAP_IP }}/api/v2/credentials/{{ item['id'] }}/"
        method: PATCH
        body:
          name: "{{ item['name'] }}"
          credential_type: "{{ item['credential_type'] }}"
          inputs:
            username: "{{ item['inputs']['username'] }}"
            password: "{{ item['inputs']['password'] }}"
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ AAP_TOKEN }}
        body_format: json
        validate_certs: false
      loop: "{{ updated_users }}"
