---
- name: Add hosts
  hosts: localhost
  vars:
    HOSTS_LIST:
      - ansible_host: 192.168.158.101
        ansible_user: "{{ lookup('env', 'ansible_user1') }}"
        ansible_password: "{{ lookup('env', 'ansible_password1') }}"
      - ansible_host: 192.168.158.102
        ansible_user: "{{ lookup('env', 'ansible_user2') }}"
        ansible_password: "{{ lookup('env', 'ansible_password2') }}"
  tasks:
    add_host:
      name: "{{ item.ansible_host }}"
      groups: runners_group
      ansible_user: "{{ item.ansible_user }}"
      ansible_password: "{{ item.ansible_password }}"
    loop: "{{ HOSTS_LIST }}"

- name: Test running playbook with multiple hosts with different credentials
  hosts: runners_group
  gather_facts: true
  tasks:
    - name: List local filesystem with df -h
      ansible.builtin.command:
        cmd: df -h